channels:
  - conda-forge
dependencies:
  - python==3.10
  - awscli
  - curl
  - ffmpeg
  - hdf5tools
  - ipywidgets
  - ipykernel
  - jupyterlab
  - jupyterlab-git
  - matplotlib
  - ncdu
  - numpy
  - pandas
  - pillow
  - pip
  - pytables
  - rclone
  - scipy
  - wget
